<?php

namespace AppBundle\Repository;

/**
 * CategoryAffiliationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryAffiliationRepository extends \Doctrine\ORM\EntityRepository
{
}
