<?php

namespace AppBundle\Repository;

/**
 * chatroom_alertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class chatroom_alertRepository extends \Doctrine\ORM\EntityRepository
{
}
