<?php

namespace AppBundle\Repository;

/**
 * ContactUSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactUSRepository extends \Doctrine\ORM\EntityRepository
{
}
