<?php

namespace AppBundle\Repository;

/**
 * CustomPageCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomPageCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
