<?php

namespace AppBundle\Repository;

/**
 * CustomPagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomPagesRepository extends \Doctrine\ORM\EntityRepository
{
}
