<?php

namespace AppBundle\Repository;

/**
 * ExampleKeyWordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExampleKeyWordRepository extends \Doctrine\ORM\EntityRepository
{
}
