<?php

namespace AppBundle\Repository;

/**
 * hasOneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hasOneRepository extends \Doctrine\ORM\EntityRepository
{
}
