<?php

namespace AppBundle\Repository;

/**
 * HistoryParticipantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryParticipantRepository extends \Doctrine\ORM\EntityRepository
{
}
