<?php

namespace AppBundle\Repository;

/**
 * inventoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class inventoryRepository extends \Doctrine\ORM\EntityRepository
{
}
