<?php

namespace AppBundle\Repository;

/**
 * LendBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LendBookRepository extends \Doctrine\ORM\EntityRepository
{
}
