<?php

namespace AppBundle\Repository;

/**
 * MessagesChatRoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessagesChatRoomRepository extends \Doctrine\ORM\EntityRepository
{
}
