<?php

namespace AppBundle\Repository;

/**
 * MessagesPrivateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessagesPrivateRepository extends \Doctrine\ORM\EntityRepository
{
}
