<?php

namespace AppBundle\Repository;

/**
 * PrivateChatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrivateChatRepository extends \Doctrine\ORM\EntityRepository
{
}
