<?php

namespace AppBundle\Repository;

/**
 * RegisterMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegisterMailRepository extends \Doctrine\ORM\EntityRepository
{
}
