<?php

namespace AppBundle\Repository;

/**
 * RejectAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RejectAddressRepository extends \Doctrine\ORM\EntityRepository
{
}
